from PyQt5.QtWidgets import QApplication, QLabel, QMainWindow, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.statusBar().addWidget(QLabel("Ready"))
"""
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1020, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 3, 110, 600))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.verticalLayoutWidget)
        self.toolBox.setMaximumSize(QtCore.QSize(110, 16777215))
        self.toolBox.setStyleSheet("")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 109, 509))
        self.page.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.page.setObjectName("page")
        self.wifiConnect = QtWidgets.QPushButton(self.page)
        self.wifiConnect.setGeometry(QtCore.QRect(0, 0, 110, 24))
        self.wifiConnect.setObjectName("wifiConnect")
        self.wifiDisconnect = QtWidgets.QPushButton(self.page)
        self.wifiDisconnect.setGeometry(QtCore.QRect(0, 31, 110, 24))
        self.wifiDisconnect.setObjectName("wifiDisconnect")
        self.wifiReconnect = QtWidgets.QPushButton(self.page)
        self.wifiReconnect.setGeometry(QtCore.QRect(0, 60, 110, 24))
        self.wifiReconnect.setCheckable(False)
        self.wifiReconnect.setObjectName("wifiReconnect")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 110, 21))
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 109, 509))
        self.page_2.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.page_2.setObjectName("page_2")
        self.wifiConnect_2 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_2.setGeometry(QtCore.QRect(0, 0, 110, 24))
        self.wifiConnect_2.setObjectName("wifiConnect_2")
        self.wifiConnect_3 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_3.setGeometry(QtCore.QRect(0, 30, 110, 24))
        self.wifiConnect_3.setObjectName("wifiConnect_3")
        self.wifiConnect_4 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_4.setGeometry(QtCore.QRect(0, 60, 110, 24))
        self.wifiConnect_4.setObjectName("wifiConnect_4")
        self.wifiConnect_5 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_5.setGeometry(QtCore.QRect(0, 90, 110, 24))
        self.wifiConnect_5.setObjectName("wifiConnect_5")
        self.wifiConnect_6 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_6.setGeometry(QtCore.QRect(0, 120, 110, 24))
        self.wifiConnect_6.setObjectName("wifiConnect_6")
        self.wifiConnect_7 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_7.setGeometry(QtCore.QRect(0, 150, 110, 24))
        self.wifiConnect_7.setObjectName("wifiConnect_7")
        self.wifiConnect_8 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_8.setGeometry(QtCore.QRect(0, 180, 110, 24))
        self.wifiConnect_8.setObjectName("wifiConnect_8")
        self.wifiConnect_9 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_9.setGeometry(QtCore.QRect(0, 210, 110, 24))
        self.wifiConnect_9.setObjectName("wifiConnect_9")
        self.wifiConnect_10 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_10.setGeometry(QtCore.QRect(0, 240, 110, 24))
        self.wifiConnect_10.setObjectName("wifiConnect_10")
        self.wifiConnect_11 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_11.setGeometry(QtCore.QRect(0, 270, 110, 24))
        self.wifiConnect_11.setObjectName("wifiConnect_11")
        self.wifiConnect_14 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_14.setGeometry(QtCore.QRect(0, 300, 110, 24))
        self.wifiConnect_14.setObjectName("wifiConnect_14")
        self.wifiConnect_15 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_15.setGeometry(QtCore.QRect(0, 330, 110, 24))
        self.wifiConnect_15.setObjectName("wifiConnect_15")
        self.wifiConnect_16 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_16.setGeometry(QtCore.QRect(0, 360, 110, 24))
        self.wifiConnect_16.setObjectName("wifiConnect_16")
        self.wifiConnect_17 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_17.setGeometry(QtCore.QRect(0, 390, 110, 24))
        self.wifiConnect_17.setObjectName("wifiConnect_17")
        self.wifiConnect_18 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_18.setGeometry(QtCore.QRect(0, 420, 110, 24))
        self.wifiConnect_18.setObjectName("wifiConnect_18")
        self.wifiConnect_19 = QtWidgets.QPushButton(self.page_2)
        self.wifiConnect_19.setGeometry(QtCore.QRect(0, 510, 110, 24))
        self.wifiConnect_19.setObjectName("wifiConnect_19")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 109, 509))
        self.page_3.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.page_3.setObjectName("page_3")
        self.wifiConnect_20 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_20.setGeometry(QtCore.QRect(0, 0, 110, 24))
        self.wifiConnect_20.setObjectName("wifiConnect_20")
        self.wifiConnect_21 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_21.setGeometry(QtCore.QRect(0, 30, 110, 24))
        self.wifiConnect_21.setObjectName("wifiConnect_21")
        self.wifiConnect_22 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_22.setGeometry(QtCore.QRect(0, 60, 110, 24))
        self.wifiConnect_22.setObjectName("wifiConnect_22")
        self.wifiConnect_23 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_23.setGeometry(QtCore.QRect(0, 90, 110, 24))
        self.wifiConnect_23.setObjectName("wifiConnect_23")
        self.wifiConnect_24 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_24.setGeometry(QtCore.QRect(0, 120, 110, 24))
        self.wifiConnect_24.setObjectName("wifiConnect_24")
        self.wifiConnect_25 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_25.setGeometry(QtCore.QRect(0, 150, 110, 24))
        self.wifiConnect_25.setObjectName("wifiConnect_25")
        self.wifiConnect_26 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_26.setGeometry(QtCore.QRect(0, 180, 110, 24))
        self.wifiConnect_26.setObjectName("wifiConnect_26")
        self.wifiConnect_27 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_27.setGeometry(QtCore.QRect(0, 210, 110, 24))
        self.wifiConnect_27.setObjectName("wifiConnect_27")
        self.wifiConnect_28 = QtWidgets.QPushButton(self.page_3)
        self.wifiConnect_28.setGeometry(QtCore.QRect(0, 240, 110, 24))
        self.wifiConnect_28.setObjectName("wifiConnect_28")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 109, 509))
        self.page_4.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.page_4.setObjectName("page_4")
        self.wifiConnect_29 = QtWidgets.QPushButton(self.page_4)
        self.wifiConnect_29.setGeometry(QtCore.QRect(0, 0, 110, 24))
        self.wifiConnect_29.setObjectName("wifiConnect_29")
        self.wifiConnect_30 = QtWidgets.QPushButton(self.page_4)
        self.wifiConnect_30.setGeometry(QtCore.QRect(0, 30, 110, 24))
        self.wifiConnect_30.setObjectName("wifiConnect_30")
        self.wifiConnect_31 = QtWidgets.QPushButton(self.page_4)
        self.wifiConnect_31.setGeometry(QtCore.QRect(0, 60, 110, 24))
        self.wifiConnect_31.setObjectName("wifiConnect_31")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 109, 509))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.page_5.setFont(font)
        self.page_5.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.page_5.setObjectName("page_5")
        self.textEdit_20 = QtWidgets.QTextEdit(self.page_5)
        self.textEdit_20.setGeometry(QtCore.QRect(0, 30, 100, 31))
        self.textEdit_20.setMaximumSize(QtCore.QSize(114, 50))
        self.textEdit_20.setObjectName("textEdit_20")
        self.textEdit_21 = QtWidgets.QTextEdit(self.page_5)
        self.textEdit_21.setGeometry(QtCore.QRect(0, 120, 101, 31))
        self.textEdit_21.setObjectName("textEdit_21")
        self.wifiConnect_32 = QtWidgets.QPushButton(self.page_5)
        self.wifiConnect_32.setGeometry(QtCore.QRect(0, 0, 110, 24))
        self.wifiConnect_32.setObjectName("wifiConnect_32")
        self.wifiConnect_33 = QtWidgets.QPushButton(self.page_5)
        self.wifiConnect_33.setGeometry(QtCore.QRect(0, 90, 110, 24))
        self.wifiConnect_33.setObjectName("wifiConnect_33")
        self.toolBox.addItem(self.page_5, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(112, 3, 900, 600))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 751, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rawdataRead = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rawdataRead.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rawdataRead.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.rawdataRead.setObjectName("rawdataRead")
        self.horizontalLayout_2.addWidget(self.rawdataRead)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_14.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_2.addWidget(self.pushButton_14)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 50, 890, 520))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_3)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 10, 75, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.textEdit_18 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_18.setGeometry(QtCore.QRect(0, 50, 151, 171))
        self.textEdit_18.setObjectName("textEdit_18")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(160, 10, 721, 271))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_9.setGeometry(QtCore.QRect(250, 410, 151, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 570, 75, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.textEdit_15 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_15.setGeometry(QtCore.QRect(90, 530, 151, 31))
        self.textEdit_15.setObjectName("textEdit_15")
        self.textEdit_17 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_17.setGeometry(QtCore.QRect(90, 570, 151, 31))
        self.textEdit_17.setObjectName("textEdit_17")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 530, 75, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.textEdit_13 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_13.setGeometry(QtCore.QRect(90, 490, 151, 31))
        self.textEdit_13.setObjectName("textEdit_13")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_11.setGeometry(QtCore.QRect(250, 450, 151, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_16 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_16.setGeometry(QtCore.QRect(250, 570, 151, 31))
        self.textEdit_16.setObjectName("textEdit_16")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_7.setGeometry(QtCore.QRect(250, 370, 151, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_4.setGeometry(QtCore.QRect(90, 330, 151, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_6.setGeometry(QtCore.QRect(90, 370, 151, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(90, 290, 151, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_14 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_14.setGeometry(QtCore.QRect(250, 530, 151, 31))
        self.textEdit_14.setObjectName("textEdit_14")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_5.setGeometry(QtCore.QRect(250, 330, 151, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 490, 75, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 290, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 330, 75, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_3.setGeometry(QtCore.QRect(250, 290, 151, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_8.setGeometry(QtCore.QRect(90, 410, 151, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_12 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_12.setGeometry(QtCore.QRect(250, 490, 151, 31))
        self.textEdit_12.setObjectName("textEdit_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 370, 75, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_10.setGeometry(QtCore.QRect(90, 450, 151, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 450, 75, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 410, 75, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 230, 54, 12))
        self.label.setObjectName("label")
        self.textEdit_19 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_19.setGeometry(QtCore.QRect(0, 250, 151, 31))
        self.textEdit_19.setObjectName("textEdit_19")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADB Monitor 1.0.4"))
        self.wifiConnect.setText(_translate("MainWindow", "WiFi Connect"))
        self.wifiDisconnect.setText(_translate("MainWindow", "WiFi disconnect"))
        self.wifiReconnect.setText(_translate("MainWindow", "Reconnect"))
        self.label_2.setText(_translate("MainWindow", "WiFi Status"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "WIFI"))
        self.wifiConnect_2.setText(_translate("MainWindow", "ShutDown"))
        self.wifiConnect_3.setText(_translate("MainWindow", "PowerKey"))
        self.wifiConnect_4.setText(_translate("MainWindow", "ScreenShot"))
        self.wifiConnect_5.setText(_translate("MainWindow", "Reboot"))
        self.wifiConnect_6.setText(_translate("MainWindow", "Home"))
        self.wifiConnect_7.setText(_translate("MainWindow", "Back"))
        self.wifiConnect_8.setText(_translate("MainWindow", "Vol_up"))
        self.wifiConnect_9.setText(_translate("MainWindow", "Vol_down"))
        self.wifiConnect_10.setText(_translate("MainWindow", "Getprop"))
        self.wifiConnect_11.setText(_translate("MainWindow", "Interrupts"))
        self.wifiConnect_14.setText(_translate("MainWindow", "CheckDevices"))
        self.wifiConnect_15.setText(_translate("MainWindow", "HideVirtual"))
        self.wifiConnect_16.setText(_translate("MainWindow", "ShowVirtual"))
        self.wifiConnect_17.setText(_translate("MainWindow", "OpenPoint"))
        self.wifiConnect_18.setText(_translate("MainWindow", "ClosePoint"))
        self.wifiConnect_19.setText(_translate("MainWindow", "PullHXFile"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "ADB"))
        self.wifiConnect_20.setText(_translate("MainWindow", "FWVersion"))
        self.wifiConnect_21.setText(_translate("MainWindow", "Reset"))
        self.wifiConnect_22.setText(_translate("MainWindow", "SenseOn"))
        self.wifiConnect_23.setText(_translate("MainWindow", "SenseOff"))
        self.wifiConnect_24.setText(_translate("MainWindow", "SelfTest"))
        self.wifiConnect_25.setText(_translate("MainWindow", "Int_en_0"))
        self.wifiConnect_26.setText(_translate("MainWindow", "Int_en_1"))
        self.wifiConnect_27.setText(_translate("MainWindow", "DriverVersion"))
        self.wifiConnect_28.setText(_translate("MainWindow", "FlashDump"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Touch"))
        self.wifiConnect_29.setText(_translate("MainWindow", "1129"))
        self.wifiConnect_30.setText(_translate("MainWindow", "2810"))
        self.wifiConnect_31.setText(_translate("MainWindow", "OpenBlight"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Display"))
        self.wifiConnect_32.setText(_translate("MainWindow", "DiagArr"))
        self.wifiConnect_33.setText(_translate("MainWindow", "UpdateFW"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Options"))
        self.rawdataRead.setText(_translate("MainWindow", "Read"))
        self.radioButton.setText(_translate("MainWindow", "DC"))
        self.radioButton_2.setText(_translate("MainWindow", "IIR"))
        self.radioButton_3.setText(_translate("MainWindow", "Other"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.pushButton_3.setText(_translate("MainWindow", "SRAM"))
        self.pushButton_13.setText(_translate("MainWindow", "Log"))
        self.pushButton_4.setText(_translate("MainWindow", "Kmsg"))
        self.pushButton_14.setText(_translate("MainWindow", "Getevent"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Rawdata show"))
        self.pushButton_12.setText(_translate("MainWindow", "Read"))
        self.pushButton_11.setText(_translate("MainWindow", "Write 7"))
        self.pushButton_10.setText(_translate("MainWindow", "Write 6"))
        self.pushButton_9.setText(_translate("MainWindow", "Write 5"))
        self.pushButton.setText(_translate("MainWindow", "Write 0"))
        self.pushButton_5.setText(_translate("MainWindow", "Write 1"))
        self.pushButton_6.setText(_translate("MainWindow", "Write 2"))
        self.pushButton_8.setText(_translate("MainWindow", "Write 4"))
        self.pushButton_7.setText(_translate("MainWindow", "Write 3"))
        self.label.setText(_translate("MainWindow", "Length"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "R/W register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Swipe Lines"))
"""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(927, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 111, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(5, 3, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LeftMainWindow = QtWidgets.QToolBox(self.verticalLayoutWidget)
        self.LeftMainWindow.setMaximumSize(QtCore.QSize(100, 600))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LeftMainWindow.setFont(font)
        self.LeftMainWindow.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.LeftMainWindow.setObjectName("LeftMainWindow")
        self.pageWifi = QtWidgets.QWidget()
        self.pageWifi.setGeometry(QtCore.QRect(0, 0, 100, 372))
        self.pageWifi.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.pageWifi.setObjectName("pageWifi")
        self.wifiConnect = QtWidgets.QPushButton(self.pageWifi)
        self.wifiConnect.setGeometry(QtCore.QRect(0, 0, 100, 25))
        self.wifiConnect.setMaximumSize(QtCore.QSize(100, 25))
        self.wifiConnect.setStyleSheet("color: rgb(0, 0, 0);")
        self.wifiConnect.setObjectName("wifiConnect")
        self.wifiDisconnect = QtWidgets.QPushButton(self.pageWifi)
        self.wifiDisconnect.setGeometry(QtCore.QRect(0, 25, 100, 25))
        self.wifiDisconnect.setMaximumSize(QtCore.QSize(100, 25))
        self.wifiDisconnect.setStyleSheet("color: rgb(0, 0, 0);")
        self.wifiDisconnect.setCheckable(False)
        self.wifiDisconnect.setObjectName("wifiDisconnect")
        self.wifiReconnect = QtWidgets.QPushButton(self.pageWifi)
        self.wifiReconnect.setGeometry(QtCore.QRect(0, 50, 100, 25))
        self.wifiReconnect.setMaximumSize(QtCore.QSize(100, 25))
        self.wifiReconnect.setStyleSheet("color: rgb(0, 0, 0);")
        self.wifiReconnect.setCheckable(False)
        self.wifiReconnect.setObjectName("wifiReconnect")
        self.wifiStatus = QtWidgets.QLabel(self.pageWifi)
        self.wifiStatus.setGeometry(QtCore.QRect(0, 80, 100, 25))
        self.wifiStatus.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.wifiStatus.setFont(font)
        self.wifiStatus.setStyleSheet("color: rgb(255, 0, 0);")
        self.wifiStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.wifiStatus.setWordWrap(False)
        self.wifiStatus.setObjectName("wifiStatus")
        self.LeftMainWindow.addItem(self.pageWifi, "")
        self.pageAdb = QtWidgets.QWidget()
        self.pageAdb.setGeometry(QtCore.QRect(0, 0, 100, 372))
        self.pageAdb.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.pageAdb.setObjectName("pageAdb")
        self.shutDown = QtWidgets.QPushButton(self.pageAdb)
        self.shutDown.setGeometry(QtCore.QRect(0, 0, 100, 25))
        self.shutDown.setMinimumSize(QtCore.QSize(100, 25))
        self.shutDown.setMaximumSize(QtCore.QSize(100, 25))
        self.shutDown.setStyleSheet("color: rgb(0, 0, 0);")
        self.shutDown.setObjectName("shutDown")
        self.powerKey = QtWidgets.QPushButton(self.pageAdb)
        self.powerKey.setGeometry(QtCore.QRect(0, 25, 100, 25))
        self.powerKey.setMaximumSize(QtCore.QSize(100, 25))
        self.powerKey.setStyleSheet("color: rgb(0, 0, 0);")
        self.powerKey.setObjectName("powerKey")
        self.screenShot = QtWidgets.QPushButton(self.pageAdb)
        self.screenShot.setGeometry(QtCore.QRect(0, 50, 100, 25))
        self.screenShot.setMaximumSize(QtCore.QSize(100, 25))
        self.screenShot.setStyleSheet("color: rgb(0, 0, 0);")
        self.screenShot.setObjectName("screenShot")
        self.reboot = QtWidgets.QPushButton(self.pageAdb)
        self.reboot.setGeometry(QtCore.QRect(0, 75, 100, 25))
        self.reboot.setMaximumSize(QtCore.QSize(100, 25))
        self.reboot.setStyleSheet("color: rgb(0, 0, 0);")
        self.reboot.setObjectName("reboot")
        self.home = QtWidgets.QPushButton(self.pageAdb)
        self.home.setGeometry(QtCore.QRect(0, 100, 100, 25))
        self.home.setMaximumSize(QtCore.QSize(100, 25))
        self.home.setStyleSheet("color: rgb(0, 0, 0);")
        self.home.setObjectName("home")
        self.back = QtWidgets.QPushButton(self.pageAdb)
        self.back.setGeometry(QtCore.QRect(0, 125, 100, 25))
        self.back.setMaximumSize(QtCore.QSize(100, 25))
        self.back.setStyleSheet("color: rgb(0, 0, 0);")
        self.back.setObjectName("back")
        self.volUp = QtWidgets.QPushButton(self.pageAdb)
        self.volUp.setGeometry(QtCore.QRect(0, 150, 100, 25))
        self.volUp.setMaximumSize(QtCore.QSize(100, 25))
        self.volUp.setStyleSheet("color: rgb(0, 0, 0);")
        self.volUp.setObjectName("volUp")
        self.volDown = QtWidgets.QPushButton(self.pageAdb)
        self.volDown.setGeometry(QtCore.QRect(0, 175, 100, 25))
        self.volDown.setMaximumSize(QtCore.QSize(100, 25))
        self.volDown.setStyleSheet("color: rgb(0, 0, 0);")
        self.volDown.setObjectName("volDown")
        self.getprop = QtWidgets.QPushButton(self.pageAdb)
        self.getprop.setGeometry(QtCore.QRect(0, 200, 100, 25))
        self.getprop.setMaximumSize(QtCore.QSize(100, 25))
        self.getprop.setStyleSheet("color: rgb(0, 0, 0);")
        self.getprop.setObjectName("getprop")
        self.interrupts = QtWidgets.QPushButton(self.pageAdb)
        self.interrupts.setGeometry(QtCore.QRect(0, 225, 100, 25))
        self.interrupts.setMaximumSize(QtCore.QSize(100, 25))
        self.interrupts.setStyleSheet("color: rgb(0, 0, 0);")
        self.interrupts.setObjectName("interrupts")
        self.checkDevices = QtWidgets.QPushButton(self.pageAdb)
        self.checkDevices.setGeometry(QtCore.QRect(0, 250, 100, 25))
        self.checkDevices.setMaximumSize(QtCore.QSize(100, 25))
        self.checkDevices.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkDevices.setObjectName("checkDevices")
        self.hideVirtual = QtWidgets.QPushButton(self.pageAdb)
        self.hideVirtual.setGeometry(QtCore.QRect(0, 275, 100, 25))
        self.hideVirtual.setMaximumSize(QtCore.QSize(100, 25))
        self.hideVirtual.setStyleSheet("color: rgb(0, 0, 0);")
        self.hideVirtual.setObjectName("hideVirtual")
        self.showVirtual = QtWidgets.QPushButton(self.pageAdb)
        self.showVirtual.setGeometry(QtCore.QRect(0, 300, 100, 25))
        self.showVirtual.setMaximumSize(QtCore.QSize(100, 25))
        self.showVirtual.setStyleSheet("color: rgb(0, 0, 0);")
        self.showVirtual.setObjectName("showVirtual")
        self.openPoint = QtWidgets.QPushButton(self.pageAdb)
        self.openPoint.setGeometry(QtCore.QRect(0, 325, 100, 25))
        self.openPoint.setMaximumSize(QtCore.QSize(100, 25))
        self.openPoint.setStyleSheet("color: rgb(0, 0, 0);")
        self.openPoint.setObjectName("openPoint")
        self.closePoint = QtWidgets.QPushButton(self.pageAdb)
        self.closePoint.setGeometry(QtCore.QRect(0, 350, 100, 25))
        self.closePoint.setMaximumSize(QtCore.QSize(100, 25))
        self.closePoint.setStyleSheet("color: rgb(0, 0, 0);")
        self.closePoint.setObjectName("closePoint")
        self.wifiConnect_19 = QtWidgets.QPushButton(self.pageAdb)
        self.wifiConnect_19.setGeometry(QtCore.QRect(0, 510, 110, 24))
        self.wifiConnect_19.setObjectName("wifiConnect_19")
        self.LeftMainWindow.addItem(self.pageAdb, "")
        self.pageTouch = QtWidgets.QWidget()
        self.pageTouch.setGeometry(QtCore.QRect(0, 0, 100, 372))
        self.pageTouch.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.pageTouch.setObjectName("pageTouch")
        self.fwVersion = QtWidgets.QPushButton(self.pageTouch)
        self.fwVersion.setGeometry(QtCore.QRect(0, 0, 100, 25))
        self.fwVersion.setMaximumSize(QtCore.QSize(100, 25))
        self.fwVersion.setStyleSheet("color: rgb(0, 0, 0);")
        self.fwVersion.setObjectName("fwVersion")
        self.reset = QtWidgets.QPushButton(self.pageTouch)
        self.reset.setGeometry(QtCore.QRect(0, 30, 100, 25))
        self.reset.setMaximumSize(QtCore.QSize(100, 25))
        self.reset.setStyleSheet("color: rgb(0, 0, 0);")
        self.reset.setObjectName("reset")
        self.senseon = QtWidgets.QPushButton(self.pageTouch)
        self.senseon.setGeometry(QtCore.QRect(0, 60, 100, 25))
        self.senseon.setMaximumSize(QtCore.QSize(100, 25))
        self.senseon.setStyleSheet("color: rgb(0, 0, 0);")
        self.senseon.setObjectName("senseon")
        self.senseoff = QtWidgets.QPushButton(self.pageTouch)
        self.senseoff.setGeometry(QtCore.QRect(0, 90, 100, 25))
        self.senseoff.setMaximumSize(QtCore.QSize(100, 25))
        self.senseoff.setStyleSheet("color: rgb(0, 0, 0);")
        self.senseoff.setObjectName("senseoff")
        self.selftest = QtWidgets.QPushButton(self.pageTouch)
        self.selftest.setGeometry(QtCore.QRect(0, 120, 100, 25))
        self.selftest.setMaximumSize(QtCore.QSize(100, 25))
        self.selftest.setStyleSheet("color: rgb(0, 0, 0);")
        self.selftest.setObjectName("selftest")
        self.inten0 = QtWidgets.QPushButton(self.pageTouch)
        self.inten0.setGeometry(QtCore.QRect(0, 150, 100, 25))
        self.inten0.setMaximumSize(QtCore.QSize(100, 25))
        self.inten0.setStyleSheet("color: rgb(0, 0, 0);")
        self.inten0.setObjectName("inten0")
        self.inten1 = QtWidgets.QPushButton(self.pageTouch)
        self.inten1.setGeometry(QtCore.QRect(0, 180, 100, 25))
        self.inten1.setMaximumSize(QtCore.QSize(100, 25))
        self.inten1.setStyleSheet("color: rgb(0, 0, 0);")
        self.inten1.setObjectName("inten1")
        self.driverVersion = QtWidgets.QPushButton(self.pageTouch)
        self.driverVersion.setGeometry(QtCore.QRect(0, 210, 100, 25))
        self.driverVersion.setMaximumSize(QtCore.QSize(100, 25))
        self.driverVersion.setStyleSheet("color: rgb(0, 0, 0);")
        self.driverVersion.setObjectName("driverVersion")
        self.flashDump = QtWidgets.QPushButton(self.pageTouch)
        self.flashDump.setGeometry(QtCore.QRect(0, 240, 100, 25))
        self.flashDump.setMaximumSize(QtCore.QSize(100, 25))
        self.flashDump.setStyleSheet("color: rgb(0, 0, 0);")
        self.flashDump.setObjectName("flashDump")
        self.LeftMainWindow.addItem(self.pageTouch, "")
        self.pageDisplay = QtWidgets.QWidget()
        self.pageDisplay.setGeometry(QtCore.QRect(0, 0, 100, 372))
        self.pageDisplay.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.pageDisplay.setObjectName("pageDisplay")
        self.d1129 = QtWidgets.QPushButton(self.pageDisplay)
        self.d1129.setGeometry(QtCore.QRect(0, 0, 100, 25))
        self.d1129.setMaximumSize(QtCore.QSize(100, 25))
        self.d1129.setStyleSheet("color: rgb(0, 0, 0);")
        self.d1129.setObjectName("d1129")
        self.d2810 = QtWidgets.QPushButton(self.pageDisplay)
        self.d2810.setGeometry(QtCore.QRect(0, 30, 100, 25))
        self.d2810.setMaximumSize(QtCore.QSize(100, 25))
        self.d2810.setStyleSheet("color: rgb(0, 0, 0);")
        self.d2810.setObjectName("d2810")
        self.openBlight = QtWidgets.QPushButton(self.pageDisplay)
        self.openBlight.setGeometry(QtCore.QRect(0, 60, 100, 25))
        self.openBlight.setMaximumSize(QtCore.QSize(100, 25))
        self.openBlight.setStyleSheet("color: rgb(0, 0, 0);")
        self.openBlight.setObjectName("openBlight")
        self.LeftMainWindow.addItem(self.pageDisplay, "")
        self.pageOptions = QtWidgets.QWidget()
        self.pageOptions.setGeometry(QtCore.QRect(0, 0, 100, 372))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pageOptions.setFont(font)
        self.pageOptions.setStyleSheet("background-color: rgb(202, 204, 183);")
        self.pageOptions.setObjectName("pageOptions")
        self.diagArrText = QtWidgets.QTextEdit(self.pageOptions)
        self.diagArrText.setGeometry(QtCore.QRect(0, 30, 99, 30))
        self.diagArrText.setMaximumSize(QtCore.QSize(100, 30))
        self.diagArrText.setStyleSheet("color: rgb(0, 0, 0);")
        self.diagArrText.setObjectName("diagArrText")
        self.updateFWText = QtWidgets.QTextEdit(self.pageOptions)
        self.updateFWText.setGeometry(QtCore.QRect(0, 120, 99, 30))
        self.updateFWText.setMaximumSize(QtCore.QSize(100, 30))
        self.updateFWText.setStyleSheet("color: rgb(0, 0, 0);")
        self.updateFWText.setObjectName("updateFWText")
        self.diagArr = QtWidgets.QPushButton(self.pageOptions)
        self.diagArr.setGeometry(QtCore.QRect(0, 0, 100, 25))
        self.diagArr.setMaximumSize(QtCore.QSize(100, 25))
        self.diagArr.setStyleSheet("color: rgb(0, 0, 0);")
        self.diagArr.setObjectName("diagArr")
        self.updateFW = QtWidgets.QPushButton(self.pageOptions)
        self.updateFW.setGeometry(QtCore.QRect(0, 90, 100, 25))
        self.updateFW.setMaximumSize(QtCore.QSize(100, 25))
        self.updateFW.setStyleSheet("color: rgb(0, 0, 0);")
        self.updateFW.setObjectName("updateFW")
        self.LeftMainWindow.addItem(self.pageOptions, "")
        self.verticalLayout.addWidget(self.LeftMainWindow)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 0, 811, 491))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TabMainWindow = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.TabMainWindow.setFont(font)
        self.TabMainWindow.setObjectName("TabMainWindow")
        self.TabRawdataShow = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.TabRawdataShow.setFont(font)
        self.TabRawdataShow.setObjectName("TabRawdataShow")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.TabRawdataShow)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 762, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rawdataRead = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rawdataRead.setMinimumSize(QtCore.QSize(100, 20))
        self.rawdataRead.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rawdataRead.setFont(font)
        self.rawdataRead.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rawdataRead.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.rawdataRead.setObjectName("rawdataRead")
        self.horizontalLayout_2.addWidget(self.rawdataRead)
        self.radioDC = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioDC.setMaximumSize(QtCore.QSize(50, 30))
        self.radioDC.setObjectName("radioDC")
        self.horizontalLayout_2.addWidget(self.radioDC)
        self.radioIIR = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioIIR.setMaximumSize(QtCore.QSize(50, 30))
        self.radioIIR.setObjectName("radioIIR")
        self.horizontalLayout_2.addWidget(self.radioIIR)
        self.radioTmp = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioTmp.setMaximumSize(QtCore.QSize(15, 30))
        self.radioTmp.setText("")
        self.radioTmp.setObjectName("radioTmp")
        self.horizontalLayout_2.addWidget(self.radioTmp)
        self.textEditDiag = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEditDiag.setMaximumSize(QtCore.QSize(60, 29))
        self.textEditDiag.setObjectName("textEditDiag")
        self.horizontalLayout_2.addWidget(self.textEditDiag)
        self.stop = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.stop.setMaximumSize(QtCore.QSize(60, 30))
        self.stop.setObjectName("stop")
        self.horizontalLayout_2.addWidget(self.stop)
        self.sram = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.sram.setMaximumSize(QtCore.QSize(60, 30))
        self.sram.setObjectName("sram")
        self.horizontalLayout_2.addWidget(self.sram)
        self.log = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.log.setMaximumSize(QtCore.QSize(60, 30))
        self.log.setObjectName("log")
        self.horizontalLayout_2.addWidget(self.log)
        self.kmsg = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.kmsg.setMaximumSize(QtCore.QSize(70, 30))
        self.kmsg.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.kmsg.setObjectName("kmsg")
        self.horizontalLayout_2.addWidget(self.kmsg)
        self.textEditKmsg = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEditKmsg.setMaximumSize(QtCore.QSize(60, 29))
        self.textEditKmsg.setObjectName("textEditKmsg")
        self.horizontalLayout_2.addWidget(self.textEditKmsg)
        self.getevent = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.getevent.setMaximumSize(QtCore.QSize(70, 30))
        self.getevent.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.getevent.setObjectName("getevent")
        self.horizontalLayout_2.addWidget(self.getevent)
        self.textEditGetevent = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEditGetevent.setMaximumSize(QtCore.QSize(60, 29))
        self.textEditGetevent.setObjectName("textEditGetevent")
        self.horizontalLayout_2.addWidget(self.textEditGetevent)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.TabRawdataShow)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 801, 431))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rawdataShowText = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_3)
        self.rawdataShowText.setObjectName("rawdataShowText")
        self.horizontalLayout_3.addWidget(self.rawdataShowText)
        self.TabMainWindow.addTab(self.TabRawdataShow, "")
        self.TabRWRegister = QtWidgets.QWidget()
        self.TabRWRegister.setObjectName("TabRWRegister")
        self.pushButtonRead = QtWidgets.QPushButton(self.TabRWRegister)
        self.pushButtonRead.setGeometry(QtCore.QRect(0, 5, 150, 30))
        self.pushButtonRead.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRead.setObjectName("pushButtonRead")
        self.textEditReadRegAddr = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditReadRegAddr.setGeometry(QtCore.QRect(0, 40, 150, 170))
        self.textEditReadRegAddr.setMaximumSize(QtCore.QSize(150, 170))
        self.textEditReadRegAddr.setObjectName("textEditReadRegAddr")
        self.readRegValShowText = QtWidgets.QTextBrowser(self.TabRWRegister)
        self.readRegValShowText.setGeometry(QtCore.QRect(160, 5, 640, 260))
        self.readRegValShowText.setObjectName("readRegValShowText")
        self.textEditWriteVal3 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteVal3.setGeometry(QtCore.QRect(320, 390, 150, 30))
        self.textEditWriteVal3.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal3.setObjectName("textEditWriteVal3")
        self.textEditWriteVal4 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteVal4.setGeometry(QtCore.QRect(320, 430, 150, 30))
        self.textEditWriteVal4.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal4.setObjectName("textEditWriteVal4")
        self.textEditWriteVal2 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteVal2.setGeometry(QtCore.QRect(320, 350, 150, 30))
        self.textEditWriteVal2.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal2.setObjectName("textEditWriteVal2")
        self.textEditWriteAddr1 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteAddr1.setGeometry(QtCore.QRect(160, 310, 150, 30))
        self.textEditWriteAddr1.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr1.setObjectName("textEditWriteAddr1")
        self.textEditWriteAddr2 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteAddr2.setGeometry(QtCore.QRect(160, 350, 150, 30))
        self.textEditWriteAddr2.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr2.setObjectName("textEditWriteAddr2")
        self.textEditWriteAddr0 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteAddr0.setGeometry(QtCore.QRect(160, 270, 150, 30))
        self.textEditWriteAddr0.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr0.setObjectName("textEditWriteAddr0")
        self.textEditWriteVal1 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteVal1.setGeometry(QtCore.QRect(320, 310, 150, 30))
        self.textEditWriteVal1.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal1.setObjectName("textEditWriteVal1")
        self.pushButtonRegWrite0 = QtWidgets.QPushButton(self.TabRWRegister)
        self.pushButtonRegWrite0.setGeometry(QtCore.QRect(0, 270, 150, 30))
        self.pushButtonRegWrite0.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite0.setObjectName("pushButtonRegWrite0")
        self.pushButtonRegWrite1 = QtWidgets.QPushButton(self.TabRWRegister)
        self.pushButtonRegWrite1.setGeometry(QtCore.QRect(0, 310, 150, 30))
        self.pushButtonRegWrite1.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite1.setObjectName("pushButtonRegWrite1")
        self.textEditWriteVal0 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteVal0.setGeometry(QtCore.QRect(320, 270, 150, 30))
        self.textEditWriteVal0.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal0.setObjectName("textEditWriteVal0")
        self.textEditWriteAddr3 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteAddr3.setGeometry(QtCore.QRect(160, 390, 150, 30))
        self.textEditWriteAddr3.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr3.setObjectName("textEditWriteAddr3")
        self.pushButtonRegWrite2 = QtWidgets.QPushButton(self.TabRWRegister)
        self.pushButtonRegWrite2.setGeometry(QtCore.QRect(0, 350, 150, 30))
        self.pushButtonRegWrite2.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite2.setObjectName("pushButtonRegWrite2")
        self.textEditWriteAddr4 = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditWriteAddr4.setGeometry(QtCore.QRect(160, 430, 150, 30))
        self.textEditWriteAddr4.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr4.setObjectName("textEditWriteAddr4")
        self.pushButtonRegWrite4 = QtWidgets.QPushButton(self.TabRWRegister)
        self.pushButtonRegWrite4.setGeometry(QtCore.QRect(0, 430, 150, 30))
        self.pushButtonRegWrite4.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite4.setObjectName("pushButtonRegWrite4")
        self.pushButtonRegWrite3 = QtWidgets.QPushButton(self.TabRWRegister)
        self.pushButtonRegWrite3.setGeometry(QtCore.QRect(0, 390, 150, 30))
        self.pushButtonRegWrite3.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite3.setObjectName("pushButtonRegWrite3")
        self.label = QtWidgets.QLabel(self.TabRWRegister)
        self.label.setGeometry(QtCore.QRect(10, 215, 60, 20))
        self.label.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEditReadRegLen = QtWidgets.QTextEdit(self.TabRWRegister)
        self.textEditReadRegLen.setGeometry(QtCore.QRect(0, 235, 150, 30))
        self.textEditReadRegLen.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditReadRegLen.setObjectName("textEditReadRegLen")
        self.TabMainWindow.addTab(self.TabRWRegister, "")
        self.TabSwiplines = QtWidgets.QWidget()
        self.TabSwiplines.setObjectName("TabSwiplines")
        self.TabMainWindow.addTab(self.TabSwiplines, "")
        self.TabHelp = QtWidgets.QWidget()
        self.TabHelp.setObjectName("TabHelp")
        self.TabHelpSubMain = QtWidgets.QTabWidget(self.TabHelp)
        self.TabHelpSubMain.setGeometry(QtCore.QRect(0, 0, 801, 461))
        self.TabHelpSubMain.setObjectName("TabHelpSubMain")
        self.TabAbout = QtWidgets.QWidget()
        self.TabAbout.setObjectName("TabAbout")
        self.aboutShowText = QtWidgets.QTextBrowser(self.TabAbout)
        self.aboutShowText.setGeometry(QtCore.QRect(2, 2, 791, 431))
        self.aboutShowText.setObjectName("aboutShowText")
        self.TabHelpSubMain.addTab(self.TabAbout, "")
        self.TabCommands = QtWidgets.QWidget()
        self.TabCommands.setObjectName("TabCommands")
        self.commandsShowText = QtWidgets.QTextBrowser(self.TabCommands)
        self.commandsShowText.setGeometry(QtCore.QRect(2, 2, 791, 431))
        self.commandsShowText.setObjectName("commandsShowText")
        self.TabHelpSubMain.addTab(self.TabCommands, "")
        self.TabMainWindow.addTab(self.TabHelp, "")
        self.horizontalLayout.addWidget(self.TabMainWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.LeftMainWindow.setCurrentIndex(1)
        self.LeftMainWindow.layout().setSpacing(0)
        self.TabMainWindow.setCurrentIndex(0)
        self.TabHelpSubMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wifiConnect.setText(_translate("MainWindow", "WiFi Connect"))
        self.wifiDisconnect.setText(_translate("MainWindow", "WiFi disconnect"))
        self.wifiReconnect.setText(_translate("MainWindow", "Reconnect"))
        self.wifiStatus.setText(_translate("MainWindow", "WiFi Status"))
        self.LeftMainWindow.setItemText(self.LeftMainWindow.indexOf(self.pageWifi), _translate("MainWindow", "WIFI"))
        self.shutDown.setText(_translate("MainWindow", "ShutDown"))
        self.powerKey.setText(_translate("MainWindow", "PowerKey"))
        self.screenShot.setText(_translate("MainWindow", "ScreenShot"))
        self.reboot.setText(_translate("MainWindow", "Reboot"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.back.setText(_translate("MainWindow", "Back"))
        self.volUp.setText(_translate("MainWindow", "Vol_up"))
        self.volDown.setText(_translate("MainWindow", "Vol_down"))
        self.getprop.setText(_translate("MainWindow", "Getprop"))
        self.interrupts.setText(_translate("MainWindow", "Interrupts"))
        self.checkDevices.setText(_translate("MainWindow", "CheckDevices"))
        self.hideVirtual.setText(_translate("MainWindow", "HideVirtual"))
        self.showVirtual.setText(_translate("MainWindow", "ShowVirtual"))
        self.openPoint.setText(_translate("MainWindow", "OpenPoint"))
        self.closePoint.setText(_translate("MainWindow", "ClosePoint"))
        self.wifiConnect_19.setText(_translate("MainWindow", "PullHXFile"))
        self.LeftMainWindow.setItemText(self.LeftMainWindow.indexOf(self.pageAdb), _translate("MainWindow", "ADB"))
        self.fwVersion.setText(_translate("MainWindow", "FWVersion"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.senseon.setText(_translate("MainWindow", "SenseOn"))
        self.senseoff.setText(_translate("MainWindow", "SenseOff"))
        self.selftest.setText(_translate("MainWindow", "SelfTest"))
        self.inten0.setText(_translate("MainWindow", "Int_en_0"))
        self.inten1.setText(_translate("MainWindow", "Int_en_1"))
        self.driverVersion.setText(_translate("MainWindow", "DriverVersion"))
        self.flashDump.setText(_translate("MainWindow", "FlashDump"))
        self.LeftMainWindow.setItemText(self.LeftMainWindow.indexOf(self.pageTouch), _translate("MainWindow", "Touch"))
        self.d1129.setText(_translate("MainWindow", "1129"))
        self.d2810.setText(_translate("MainWindow", "2810"))
        self.openBlight.setText(_translate("MainWindow", "OpenBlight"))
        self.LeftMainWindow.setItemText(self.LeftMainWindow.indexOf(self.pageDisplay), _translate("MainWindow", "Display"))
        self.diagArr.setText(_translate("MainWindow", "DiagArr"))
        self.updateFW.setText(_translate("MainWindow", "UpdateFW"))
        self.LeftMainWindow.setItemText(self.LeftMainWindow.indexOf(self.pageOptions), _translate("MainWindow", "Options"))
        self.rawdataRead.setText(_translate("MainWindow", "Read"))
        self.radioDC.setText(_translate("MainWindow", "DC"))
        self.radioIIR.setText(_translate("MainWindow", "IIR"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.sram.setText(_translate("MainWindow", "SRAM"))
        self.log.setText(_translate("MainWindow", "Log"))
        self.kmsg.setText(_translate("MainWindow", "Kmsg"))
        self.getevent.setText(_translate("MainWindow", "Getevent"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.TabRawdataShow), _translate("MainWindow", "Rawdata show"))
        self.pushButtonRead.setText(_translate("MainWindow", "Read"))
        self.pushButtonRegWrite0.setText(_translate("MainWindow", "Write 0"))
        self.pushButtonRegWrite1.setText(_translate("MainWindow", "Write 1"))
        self.pushButtonRegWrite2.setText(_translate("MainWindow", "Write 2"))
        self.pushButtonRegWrite4.setText(_translate("MainWindow", "Write 4"))
        self.pushButtonRegWrite3.setText(_translate("MainWindow", "Write 3"))
        self.label.setText(_translate("MainWindow", "Length"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.TabRWRegister), _translate("MainWindow", "R/W register"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.TabSwiplines), _translate("MainWindow", "Swipe Lines"))
        self.TabHelpSubMain.setTabText(self.TabHelpSubMain.indexOf(self.TabAbout), _translate("MainWindow", "About"))
        self.TabHelpSubMain.setTabText(self.TabHelpSubMain.indexOf(self.TabCommands), _translate("MainWindow", "Commands"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.TabHelp), _translate("MainWindow", "Help"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
